server:
  port: 8080
spring:
  application:
    name: learn-route-api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/practice?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: 123456789
  redis:
    database: 0
    url: redis://127.0.0.1:6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml